export type Radical = {
  char: string;
  hanViet: string;
  image?: string; // Thêm đường dẫn hình ảnh (tùy chọn)
  meaning: string;
};
const BASE_URL = import.meta.env.BASE_URL;
export const allRadicals: Radical[] = [
  { char: "一", hanViet: "nhất", meaning: "một", image: `${BASE_URL}images/radicals/nhat.png` },
  { char: "丨", hanViet: "cổn", meaning: "nét sổ", image: `${BASE_URL}images/radicals/conn.png` },
  { char: "丶", hanViet: "chủ", meaning: "nét chấm", image: `${BASE_URL}images/radicals/chu.png` },
  { char: "丿", hanViet: "phiệt", meaning: "nét phẩy", image: `${BASE_URL}images/radicals/phiet.png` },
  { char: "乙", hanViet: "ất", meaning: "vị trí thứ 2 trong thiên can", image: `${BASE_URL}images/radicals/at.png` },
  { char: "亅", hanViet: "quyết", meaning: "nét sổ có móc", image: `${BASE_URL}images/radicals/quyet.png` },
  { char: "二", hanViet: "nhị", meaning: "hai", image: `${BASE_URL}images/radicals/nhi.png` },
  { char: "亠", hanViet: "đầu", meaning: "cái đầu", image: `${BASE_URL}images/radicals/dau.png` },
  { char: "人", hanViet: "nhân", meaning: "người", image: `${BASE_URL}images/radicals/nhan.png` },
  { char: "亻", hanViet: "nhân đứng", meaning: "người (biến thể)", image: `${BASE_URL}images/radicals/nhan dung.png` },
  { char: "𠂉", hanViet: "nhân nằm", meaning: "người (biến thể)", image: `${BASE_URL}images/radicals/nhan nam.png` },
  { char: "儿", hanViet: "nhi", meaning: "trẻ con" },
  { char: "入", hanViet: "nhập", meaning: "vào" },
  { char: "八", hanViet: "bát", meaning: "tám", image: `${BASE_URL}images/radicals/so tam.png` },
  { char: "冂", hanViet: "quynh", meaning: "vùng biên giới xa" },
  { char: "冖", hanViet: "mịch", meaning: "trùm khăn lên" },
  { char: "冫", hanViet: "băng", meaning: "nước đá" },
  { char: "几", hanViet: "kỷ", meaning: "ghế dựa" },
  { char: "凵", hanViet: "khảm", meaning: "há miệng" },
  { char: "刀", hanViet: "đao", meaning: "con dao" },
  { char: "刂", hanViet: "đao đứng", meaning: "con dao (biến thể)" },
  { char: "力", hanViet: "lực", meaning: "sức lực" },
  { char: "勹", hanViet: "bao", meaning: "bao bọc" },
  { char: "匕", hanViet: "chủy", meaning: "cái thìa" },
  { char: "匚", hanViet: "phương", meaning: "tủ đựng" },
  { char: "匸", hanViet: "hệ", meaning: "che đậy, giấu giếm" },
  { char: "十", hanViet: "thập", meaning: "mười" },
  { char: "卜", hanViet: "bốc", meaning: "xem bói" },
  { char: "卩", hanViet: "tiết", meaning: "đốt tre" },
  { char: "厂", hanViet: "hán", meaning: "sườn núi, vách đá" },
  { char: "厶", hanViet: "khư", meaning: "riêng tư" },
  { char: "又", hanViet: "hựu", meaning: "lại nữa, một lần nữa" },
  { char: "口", hanViet: "khẩu", meaning: "cái miệng" },
  { char: "囗", hanViet: "vi", meaning: "vây quanh" },
  { char: "土", hanViet: "thổ", meaning: "đất" },
  { char: "士", hanViet: "sĩ", meaning: "kẻ sĩ" },
  { char: "夂", hanViet: "trĩ", meaning: "đến sau" },
  { char: "夊", hanViet: "tuy", meaning: "đi chậm" },
  { char: "夕", hanViet: "tịch", meaning: "đêm tối" },
  { char: "大", hanViet: "đại", meaning: "to lớn" },
  { char: "女", hanViet: "nữ", meaning: "phụ nữ" },
  { char: "子", hanViet: "tử", meaning: "con" },
  { char: "宀", hanViet: "miên", meaning: "mái nhà" },
  { char: "寸", hanViet: "thốn", meaning: "tấc" },
  { char: "小", hanViet: "tiểu", meaning: "nhỏ" },
  { char: "尢", hanViet: "uông", meaning: "yếu đuối" },
  { char: "尸", hanViet: "thi", meaning: "xác chết" },
  { char: "屮", hanViet: "triệt", meaning: "mầm non" },
  { char: "山", hanViet: "sơn", meaning: "núi" },
  { char: "巛", hanViet: "xuyên", meaning: "sông" },
  { char: "工", hanViet: "công", meaning: "công việc" },
  { char: "己", hanViet: "kỷ", meaning: "bản thân" },
  { char: "巾", hanViet: "cân", meaning: "cái khăn" },
  { char: "干", hanViet: "can", meaning: "thiên can" },
  { char: "幺", hanViet: "yêu", meaning: "nhỏ nhắn" },
  { char: "广", hanViet: "nghiễm", meaning: "mái nhà" },
  { char: "廴", hanViet: "dẫn", meaning: "bước dài" },
  { char: "廾", hanViet: "củng", meaning: "chắp tay" },
  { char: "弋", hanViet: "dặc", meaning: "bắn, chiếm lấy" },
  { char: "弓", hanViet: "cung", meaning: "cái cung" },
  { char: "彐", hanViet: "kệ", meaning: "đầu con nhím" },
  { char: "彡", hanViet: "sam", meaning: "lông, tóc" },
  { char: "彳", hanViet: "xích", meaning: "bước chân trái" },
  { char: "心", hanViet: "tâm", meaning: "trái tim" },
  { char: "忄", hanViet: "tâm đứng", meaning: "trái tim (biến thể)" },
  { char: "戈", hanViet: "qua", meaning: "cây qua (vũ khí)" },
  { char: "戶", hanViet: "hộ", meaning: "cửa một cánh" },
  { char: "手", hanViet: "thủ", meaning: "tay" },
  { char: "扌", hanViet: "thủ", meaning: "tay (biến thể)" },
  { char: "支", hanViet: "chi", meaning: "cành nhánh" },
  { char: "攴", hanViet: "phộc", meaning: "đánh khẽ" },
  { char: "文", hanViet: "văn", meaning: "văn vẻ, văn chương" },
  { char: "斗", hanViet: "đẩu", meaning: "cái đấu" },
  { char: "斤", hanViet: "cân", meaning: "cái búa" },
  { char: "方", hanViet: "phương", meaning: "phương hướng" },
  { char: "无", hanViet: "vô", meaning: "không" },
  { char: "日", hanViet: "nhật", meaning: "ngày, mặt trời" },
  { char: "曰", hanViet: "viết", meaning: "nói rằng" },
  { char: "月", hanViet: "nguyệt", meaning: "tháng, mặt trăng" },
  { char: "木", hanViet: "mộc", meaning: "cây" },
  { char: "欠", hanViet: "khiếm", meaning: "thiếu, nợ" },
  { char: "止", hanViet: "chỉ", meaning: "dừng lại" },
  { char: "歹", hanViet: "đãi", meaning: "xấu xa, tệ hại" },
  { char: "殳", hanViet: "thù", meaning: "binh khí dài" },
  { char: "毋", hanViet: "vô", meaning: "chớ, đừng" },
  { char: "比", hanViet: "tỷ", meaning: "so sánh" },
  { char: "毛", hanViet: "mao", meaning: "lông" },
  { char: "氏", hanViet: "thị", meaning: "họ" },
  { char: "气", hanViet: "khí", meaning: "hơi nước" },
  { char: "水", hanViet: "thủy", meaning: "nước" },
  { char: "氵", hanViet: "chấm thủy", meaning: "nước (biến thể)" },
  { char: "火", hanViet: "hỏa", meaning: "lửa" },
  { char: "灬", hanViet: "hỏa", meaning: "lửa (biến thể)" },
  { char: "爪", hanViet: "trảo", meaning: "móng vuốt" },
  { char: "米", hanViet: "mễ", meaning: "gạo" },
  { char: "父", hanViet: "phụ", meaning: "cha" },
  { char: "爻", hanViet: "hào", meaning: "hào陰dương" },
  { char: "爿", hanViet: "tường", meaning: "mảnh gỗ, cái giường" },
  { char: "片", hanViet: "phiến", meaning: "mảnh, tấm" },
  { char: "牙", hanViet: "nha", meaning: "răng" },
  { char: "牛", hanViet: "ngưu", meaning: "trâu" },
  { char: "犬", hanViet: "khuyển", meaning: "chó" },
  { char: "玄", hanViet: "huyền", meaning: "màu đen huyền" },
  { char: "玉", hanViet: "ngọc", meaning: "đá quý" },
  { char: "瓜", hanViet: "qua", meaning: "quả dưa" },
  { char: "瓦", hanViet: "ngõa", meaning: "ngói" },
  { char: "甘", hanViet: "cam", meaning: "ngọt" },
  { char: "生", hanViet: "sinh", meaning: "sinh đẻ, sinh sống" },
  { char: "用", hanViet: "dụng", meaning: "dùng" },
  { char: "田", hanViet: "điền", meaning: "ruộng" },
  { char: "疋", hanViet: "thất", meaning: "đơn vị đo chiều dài" },
  { char: "疒", hanViet: "nạch", meaning: "bệnh tật" },
  { char: "癶", hanViet: "bát", meaning: "gạt ngược lại" },
  { char: "白", hanViet: "bạch", meaning: "màu trắng" },
  { char: "皮", hanViet: "bì", meaning: "da" },
  { char: "皿", hanViet: "mãnh", meaning: "bát đĩa" },
  { char: "目", hanViet: "mục", meaning: "mắt" },
  { char: "矛", hanViet: "mâu", meaning: "cây giáo" },
  { char: "矢", hanViet: "thỉ", meaning: "cây tên, mũi tên" },
  { char: "石", hanViet: "thạch", meaning: "đá" },
  { char: "示", hanViet: "thị", meaning: "chỉ thị, thần đất" },
  { char: "禸", hanViet: "nhựu", meaning: "vết chân" },
  { char: "禾", hanViet: "hòa", meaning: "lúa" },
  { char: "穴", hanViet: "huyệt", meaning: "hang" },
  { char: "立", hanViet: "lập", meaning: "đứng" },
  { char: "竹", hanViet: "trúc", meaning: "tre" },
  { char: "糸", hanViet: "mịch", meaning: "sợi tơ" },
  { char: "缶", hanViet: "phẫu", meaning: "đồ sành" },
  { char: "网", hanViet: "võng", meaning: "lưới" },
  { char: "羊", hanViet: "dương", meaning: "con dê" },
  { char: "羽", hanViet: "vũ", meaning: "lông vũ" },
  { char: "老", hanViet: "lão", meaning: "già" },
  { char: "而", hanViet: "nhi", meaning: "mà, và" },
  { char: "耒", hanViet: "lỗi", meaning: "cái cày" },
  { char: "耳", hanViet: "nhĩ", meaning: "tai" },
  { char: "聿", hanViet: "duật", meaning: "cây bút" },
  { char: "肉", hanViet: "nhục", meaning: "thịt" },
  { char: "臣", hanViet: "thần", meaning: "bầy tôi" },
  { char: "自", hanViet: "tự", meaning: "tự bản thân" },
  { char: "至", hanViet: "chí", meaning: "đến" },
  { char: "臼", hanViet: "cữu", meaning: "cái cối" },
  { char: "舌", hanViet: "thiệt", meaning: "cái lưỡi" },
  { char: "舛", hanViet: "suyễn", meaning: "sai suyễn" },
  { char: "舟", hanViet: "chu", meaning: "cái thuyền" },
  { char: "艮", hanViet: "cấn", meaning: "quẻ cấn, dừng" },
  { char: "色", hanViet: "sắc", meaning: "màu sắc" },
  { char: "艹", hanViet: "thảo", meaning: "cỏ (biến thể)" },
  { char: "虍", hanViet: "hổ", meaning: "con hổ" },
  { char: "虫", hanViet: "trùng", meaning: "sâu bọ" },
  { char: "血", hanViet: "huyết", meaning: "máu" },
  { char: "行", hanViet: "hành", meaning: "đi" },
  { char: "衣", hanViet: "y", meaning: "áo" },
  { char: "西", hanViet: "tây", meaning: "phía tây" },
  { char: "見", hanViet: "kiến", meaning: "nhìn, thấy" },
  { char: "角", hanViet: "giác", meaning: "góc, sừng" },
  { char: "言", hanViet: "ngôn", meaning: "lời nói" },
  { char: "谷", hanViet: "cốc", meaning: "thung lũng" },
  { char: "豆", hanViet: "đậu", meaning: "hạt đậu" },
  { char: "豕", hanViet: "thỉ", meaning: "con heo" },
  { char: "豸", hanViet: "trãi", meaning: "loài sâu bọ" },
  { char: "貝", hanViet: "bối", meaning: "vỏ sò" },
  { char: "赤", hanViet: "xích", meaning: "màu đỏ" },
  { char: "走", hanViet: "tẩu", meaning: "chạy" },
  { char: "足", hanViet: "túc", meaning: "chân" },
  { char: "身", hanViet: "thân", meaning: "thân thể" },
  { char: "車", hanViet: "xa", meaning: "xe" },
  { char: "辛", hanViet: "tân", meaning: "cay" },
  { char: "辰", hanViet: "thần", meaning: "con rồng" },
  { char: "辵", hanViet: "sước", meaning: "chợt đi chợt dừng" },
  { char: "邑", hanViet: "ấp", meaning: "vùng đất, xóm làng" },
  { char: "酉", hanViet: "dậu", meaning: "con gà" },
  { char: "釆", hanViet: "biện", meaning: "phân biệt" },
  { char: "里", hanViet: "lý", meaning: "làng, dặm" },
  { char: "金", hanViet: "kim", meaning: "kim loại, vàng" },
  { char: "長", hanViet: "trường", meaning: "dài" },
  { char: "門", hanViet: "môn", meaning: "cửa" },
  { char: "阜", hanViet: "phụ", meaning: "gò đất" },
  { char: "隶", hanViet: "đãi", meaning: "kịp, kịp đến" },
  { char: "隹", hanViet: "chuy", meaning: "chim đuôi ngắn" },
  { char: "雨", hanViet: "vũ", meaning: "mưa" },
  { char: "青", hanViet: "thanh", meaning: "màu xanh" },
  { char: "非", hanViet: "phi", meaning: "không" },
  { char: "面", hanViet: "diện", meaning: "mặt" },
  { char: "革", hanViet: "cách", meaning: "da thú" },
  { char: "韋", hanViet: "vi", meaning: "da đã thuộc" },
  { char: "韭", hanViet: "cửu", meaning: "hẹ" },
  { char: "音", hanViet: "âm", meaning: "âm thanh" },
  { char: "頁", hanViet: "hiệt", meaning: "trang giấy" },
  { char: "風", hanViet: "phong", meaning: "gió" },
  { char: "飛", hanViet: "phi", meaning: "bay" },
  { char: "食", hanViet: "thực", meaning: "ăn" },
  { char: "首", hanViet: "thủ", meaning: "đầu" },
  { char: "香", hanViet: "hương", meaning: "mùi thơm" },
  { char: "馬", hanViet: "mã", meaning: "ngựa" },
  { char: "骨", hanViet: "cốt", meaning: "xương" },
  { char: "高", hanViet: "cao", meaning: "cao" },
  { char: "髟", hanViet: "tiêu", meaning: "tóc dài" },
  { char: "鬥", hanViet: "đấu", meaning: "chiến đấu" },
  { char: "鬯", hanViet: "sưởng", meaning: "rượu nếp" },
  { char: "鬲", hanViet: "cách", meaning: "cái nồi" },
  { char: "鬼", hanViet: "quỷ", meaning: "ma quỷ" },
  { char: "魚", hanViet: "ngư", meaning: "cá" },
  { char: "鳥", hanViet: "điểu", meaning: "chim" },
  { char: "鹵", hanViet: "lỗ", meaning: "đất mặn" },
  { char: "鹿", hanViet: "lộc", meaning: "con hươu" },
  { char: "麥", hanViet: "mạch", meaning: "lúa mạch" },
  { char: "麻", hanViet: "ma", meaning: "cây gai" },
  { char: "黃", hanViet: "hoàng", meaning: "màu vàng" },
  { char: "黍", hanViet: "thử", meaning: "lúa nếp" },
  { char: "黒", hanViet: "hắc", meaning: "màu đen" },
  { char: "黹", hanViet: "chỉ", meaning: "may vá" },
  { char: "黽", hanViet: "mãnh", meaning: "con ếch" },
  { char: "鼎", hanViet: "đỉnh", meaning: "cái đỉnh" },
  { char: "鼓", hanViet: "cổ", meaning: "cái trống" },
  { char: "鼠", hanViet: "thử", meaning: "con chuột" },
  { char: "鼻", hanViet: "tỵ", meaning: "cái mũi" },
  { char: "齊", hanViet: "tề", meaning: "ngay ngắn" },
  { char: "齒", hanViet: "xỉ", meaning: "răng" },
  { char: "龍", hanViet: "long", meaning: "con rồng" },
  { char: "龜", hanViet: "quy", meaning: "con rùa" },
  { char: "龠", hanViet: "thược", meaning: "cái sáo" },
];