export type Radical = {
  char: string;
  hanViet: string;
  image?: string; // Thêm đường dẫn hình ảnh (tùy chọn)
  meaning: string;
  strokes: number;
};
const BASE_URL = import.meta.env.BASE_URL;
export const allRadicals: Radical[] = [
  { char: "一", hanViet: "nhất", meaning: "một", strokes: 1, image: `${BASE_URL}images/radicals/nhat.png` },
  { char: "丨", hanViet: "cổn", meaning: "nét sổ", strokes: 1, image: `${BASE_URL}images/radicals/conn.png` },
  { char: "丶", hanViet: "chủ", meaning: "nét chấm", strokes: 1, image: `${BASE_URL}images/radicals/chu.png` },
  { char: "丿", hanViet: "phiệt", meaning: "nét phẩy", strokes: 1, image: `${BASE_URL}images/radicals/phiet.png` },
  { char: "乙", hanViet: "ất", meaning: "vị trí thứ 2 trong thiên can", strokes: 1, image: `${BASE_URL}images/radicals/at.png` },
  { char: "亅", hanViet: "quyết", meaning: "nét sổ có móc", strokes: 1, image: `${BASE_URL}images/radicals/quyet.png` },
  { char: "二", hanViet: "nhị", meaning: "hai", strokes: 2, image: `${BASE_URL}images/radicals/nhi.png` },
  { char: "亠", hanViet: "đầu", meaning: "cái đầu", strokes: 2, image: `${BASE_URL}images/radicals/dau.png` },
  { char: "人", hanViet: "nhân", meaning: "người", strokes: 2, image: `${BASE_URL}images/radicals/nhan.png` },
  { char: "亻", hanViet: "nhân đứng", meaning: "người (biến thể)", strokes: 2, image: `${BASE_URL}images/radicals/nhan dung.png` },
  { char: "𠂉", hanViet: "nhân nằm", meaning: "người (biến thể)", strokes: 2, image: `${BASE_URL}images/radicals/nhan nam.png` },
  { char: "儿", hanViet: "nhi", meaning: "trẻ con", strokes: 2 },
  { char: "入", hanViet: "nhập", meaning: "vào", strokes: 2 },
  { char: "八", hanViet: "bát", meaning: "tám", strokes: 2, image: `${BASE_URL}images/radicals/so tam.png` },
  { char: "冂", hanViet: "quynh", meaning: "vùng biên giới xa", strokes: 2 , image: `${BASE_URL}images/radicals/quynh.png`},
  { char: "冖", hanViet: "mịch", meaning: "trùm khăn lên", strokes: 2 , image: `${BASE_URL}images/radicals/mich.png`},
  { char: "冫", hanViet: "băng", meaning: "nước đá", strokes: 2 , image: `${BASE_URL}images/radicals/bang.png`},
  { char: "几", hanViet: "kỷ", meaning: "ghế dựa", strokes: 2 , image: `${BASE_URL}images/radicals/ky.png`},
  { char: "凵", hanViet: "khảm", meaning: "há miệng", strokes: 2 , image: `${BASE_URL}images/radicals/kham.png`},
  { char: "刀", hanViet: "đao", meaning: "con dao", strokes: 2 , image: `${BASE_URL}images/radicals/dao.png`},
  { char: "刂", hanViet: "đao đứng", meaning: "con dao (biến thể)", strokes: 2, image: `${BASE_URL}images/radicals/bo dao.png` },
  { char: "力", hanViet: "lực", meaning: "sức lực", strokes: 2, image: `${BASE_URL}images/radicals/luc.png` },
  { char: "勹", hanViet: "bao", meaning: "bao bọc", strokes: 2, image: `${BASE_URL}images/radicals/bao.png` },
  { char: "匕", hanViet: "chủy", meaning: "cái thìa", strokes: 2, image: `${BASE_URL}images/radicals/chuy.png` },
  { char: "匚", hanViet: "phương", meaning: "tủ đựng", strokes: 2 },
  { char: "匸", hanViet: "hệ", meaning: "che đậy, giấu giếm", strokes: 2 },
  { char: "十", hanViet: "thập", meaning: "mười", strokes: 2 },
  { char: "卜", hanViet: "bốc", meaning: "xem bói", strokes: 2 },
  { char: "卩", hanViet: "tiết", meaning: "đốt tre", strokes: 2 },
  { char: "厂", hanViet: "hán", meaning: "sườn núi, vách đá", strokes: 2 },
  { char: "厶", hanViet: "khư", meaning: "riêng tư", strokes: 2 },
  { char: "又", hanViet: "hựu", meaning: "lại nữa, một lần nữa", strokes: 2 },
  { char: "口", hanViet: "khẩu", meaning: "cái miệng", strokes: 3 },
  { char: "囗", hanViet: "vi", meaning: "vây quanh", strokes: 3 },
  { char: "土", hanViet: "thổ", meaning: "đất", strokes: 3 },
  { char: "士", hanViet: "sĩ", meaning: "kẻ sĩ", strokes: 3 },
  { char: "夂", hanViet: "trĩ", meaning: "đến sau", strokes: 3 },
  { char: "夊", hanViet: "tuy", meaning: "đi chậm", strokes: 3 },
  { char: "夕", hanViet: "tịch", meaning: "đêm tối", strokes: 3 },
  { char: "大", hanViet: "đại", meaning: "to lớn", strokes: 3 },
  { char: "女", hanViet: "nữ", meaning: "phụ nữ", strokes: 3 },
  { char: "子", hanViet: "tử", meaning: "con", strokes: 3 },
  { char: "宀", hanViet: "miên", meaning: "mái nhà", strokes: 3 },
  { char: "寸", hanViet: "thốn", meaning: "tấc", strokes: 3 },
  { char: "小", hanViet: "tiểu", meaning: "nhỏ", strokes: 3 },
  { char: "尢", hanViet: "uông", meaning: "yếu đuối", strokes: 3 },
  { char: "尸", hanViet: "thi", meaning: "xác chết", strokes: 3 },
  { char: "屮", hanViet: "triệt", meaning: "mầm non", strokes: 3 },
  { char: "山", hanViet: "sơn", meaning: "núi", strokes: 3 },
  { char: "巛", hanViet: "xuyên", meaning: "sông", strokes: 3 },
  { char: "工", hanViet: "công", meaning: "công việc", strokes: 3 },
  { char: "己", hanViet: "kỷ", meaning: "bản thân", strokes: 3 },
  { char: "巾", hanViet: "cân", meaning: "cái khăn", strokes: 3 },
  { char: "干", hanViet: "can", meaning: "thiên can", strokes: 3 },
  { char: "幺", hanViet: "yêu", meaning: "nhỏ nhắn", strokes: 3 },
  { char: "广", hanViet: "nghiễm", meaning: "mái nhà", strokes: 3 },
  { char: "廴", hanViet: "dẫn", meaning: "bước dài", strokes: 3 },
  { char: "廾", hanViet: "củng", meaning: "chắp tay", strokes: 3 },
  { char: "弋", hanViet: "dặc", meaning: "bắn, chiếm lấy", strokes: 3 },
  { char: "弓", hanViet: "cung", meaning: "cái cung", strokes: 3 },
  { char: "彐", hanViet: "kệ", meaning: "đầu con nhím", strokes: 3 },
  { char: "彡", hanViet: "sam", meaning: "lông, tóc", strokes: 3 },
  { char: "彳", hanViet: "xích", meaning: "bước chân trái", strokes: 3 },
  { char: "心", hanViet: "tâm", meaning: "trái tim", strokes: 4 },
  { char: "忄", hanViet: "tâm đứng", meaning: "trái tim (biến thể)", strokes: 4 },
  { char: "戈", hanViet: "qua", meaning: "cây qua (vũ khí)", strokes: 4 },
  { char: "戶", hanViet: "hộ", meaning: "cửa một cánh", strokes: 4 },
  { char: "手", hanViet: "thủ", meaning: "tay", strokes: 4 },
  { char: "扌", hanViet: "thủ", meaning: "tay (biến thể)", strokes: 4 },
  { char: "支", hanViet: "chi", meaning: "cành nhánh", strokes: 4 },
  { char: "攴", hanViet: "phộc", meaning: "đánh khẽ", strokes: 4 },
  { char: "文", hanViet: "văn", meaning: "văn vẻ, văn chương", strokes: 4 },
  { char: "斗", hanViet: "đẩu", meaning: "cái đấu", strokes: 4 },
  { char: "斤", hanViet: "cân", meaning: "cái búa", strokes: 4 },
  { char: "方", hanViet: "phương", meaning: "phương hướng", strokes: 4 },
  { char: "无", hanViet: "vô", meaning: "không", strokes: 4 },
  { char: "日", hanViet: "nhật", meaning: "ngày, mặt trời", strokes: 4 },
  { char: "曰", hanViet: "viết", meaning: "nói rằng", strokes: 4 },
  { char: "月", hanViet: "nguyệt", meaning: "tháng, mặt trăng", strokes: 4 },
  { char: "木", hanViet: "mộc", meaning: "cây", strokes: 4 },
  { char: "欠", hanViet: "khiếm", meaning: "thiếu, nợ", strokes: 4 },
  { char: "止", hanViet: "chỉ", meaning: "dừng lại", strokes: 4 },
  { char: "歹", hanViet: "đãi", meaning: "xấu xa, tệ hại", strokes: 4 },
  { char: "殳", hanViet: "thù", meaning: "binh khí dài", strokes: 4 },
  { char: "毋", hanViet: "vô", meaning: "chớ, đừng", strokes: 4 },
  { char: "比", hanViet: "tỷ", meaning: "so sánh", strokes: 4 },
  { char: "毛", hanViet: "mao", meaning: "lông", strokes: 4 },
  { char: "氏", hanViet: "thị", meaning: "họ", strokes: 4 },
  { char: "气", hanViet: "khí", meaning: "hơi nước", strokes: 4 },
  { char: "水", hanViet: "thủy", meaning: "nước", strokes: 4 },
  { char: "氵", hanViet: "chấm thủy", meaning: "nước (biến thể)", strokes: 3 },
  { char: "火", hanViet: "hỏa", meaning: "lửa", strokes: 4 },
  { char: "灬", hanViet: "hỏa", meaning: "lửa (biến thể)", strokes: 4 },
  { char: "爪", hanViet: "trảo", meaning: "móng vuốt", strokes: 4 },
  { char: "米", hanViet: "mễ", meaning: "gạo", strokes: 6 },
  { char: "父", hanViet: "phụ", meaning: "cha", strokes: 4 },
  { char: "爻", hanViet: "hào", meaning: "hào陰dương", strokes: 4 },
  { char: "爿", hanViet: "tường", meaning: "mảnh gỗ, cái giường", strokes: 4 },
  { char: "片", hanViet: "phiến", meaning: "mảnh, tấm", strokes: 4 },
  { char: "牙", hanViet: "nha", meaning: "răng", strokes: 4 },
  { char: "牛", hanViet: "ngưu", meaning: "trâu", strokes: 4 },
  { char: "犬", hanViet: "khuyển", meaning: "chó", strokes: 4 },
  { char: "玄", hanViet: "huyền", meaning: "màu đen huyền", strokes: 5 },
  { char: "玉", hanViet: "ngọc", meaning: "đá quý", strokes: 5 },
  { char: "瓜", hanViet: "qua", meaning: "quả dưa", strokes: 5 },
  { char: "瓦", hanViet: "ngõa", meaning: "ngói", strokes: 5 },
  { char: "甘", hanViet: "cam", meaning: "ngọt", strokes: 5 },
  { char: "生", hanViet: "sinh", meaning: "sinh đẻ, sinh sống", strokes: 5 },
  { char: "用", hanViet: "dụng", meaning: "dùng", strokes: 5 },
  { char: "田", hanViet: "điền", meaning: "ruộng", strokes: 5 },
  { char: "疋", hanViet: "thất", meaning: "đơn vị đo chiều dài", strokes: 5 },
  { char: "疒", hanViet: "nạch", meaning: "bệnh tật", strokes: 5 },
  { char: "癶", hanViet: "bát", meaning: "gạt ngược lại", strokes: 5 },
  { char: "白", hanViet: "bạch", meaning: "màu trắng", strokes: 5 },
  { char: "皮", hanViet: "bì", meaning: "da", strokes: 5 },
  { char: "皿", hanViet: "mãnh", meaning: "bát đĩa", strokes: 5 },
  { char: "目", hanViet: "mục", meaning: "mắt", strokes: 5 },
  { char: "矛", hanViet: "mâu", meaning: "cây giáo", strokes: 5 },
  { char: "矢", hanViet: "thỉ", meaning: "cây tên, mũi tên", strokes: 5 },
  { char: "石", hanViet: "thạch", meaning: "đá", strokes: 5 },
  { char: "示", hanViet: "thị", meaning: "chỉ thị, thần đất", strokes: 5 },
  { char: "禸", hanViet: "nhựu", meaning: "vết chân", strokes: 5 },
  { char: "禾", hanViet: "hòa", meaning: "lúa", strokes: 5 },
  { char: "穴", hanViet: "huyệt", meaning: "hang", strokes: 5 },
  { char: "立", hanViet: "lập", meaning: "đứng", strokes: 5 },
  { char: "竹", hanViet: "trúc", meaning: "tre", strokes: 6 },
  { char: "糸", hanViet: "mịch", meaning: "sợi tơ", strokes: 6 },
  { char: "缶", hanViet: "phẫu", meaning: "đồ sành", strokes: 6 },
  { char: "网", hanViet: "võng", meaning: "lưới", strokes: 6 },
  { char: "羊", hanViet: "dương", meaning: "con dê", strokes: 6 },
  { char: "羽", hanViet: "vũ", meaning: "lông vũ", strokes: 6 },
  { char: "老", hanViet: "lão", meaning: "già", strokes: 6 },
  { char: "而", hanViet: "nhi", meaning: "mà, và", strokes: 6 },
  { char: "耒", hanViet: "lỗi", meaning: "cái cày", strokes: 6 },
  { char: "耳", hanViet: "nhĩ", meaning: "tai", strokes: 6 },
  { char: "聿", hanViet: "duật", meaning: "cây bút", strokes: 6 },
  { char: "肉", hanViet: "nhục", meaning: "thịt", strokes: 6 },
  { char: "臣", hanViet: "thần", meaning: "bầy tôi", strokes: 6 },
  { char: "自", hanViet: "tự", meaning: "tự bản thân", strokes: 6 },
  { char: "至", hanViet: "chí", meaning: "đến", strokes: 6 },
  { char: "臼", hanViet: "cữu", meaning: "cái cối", strokes: 6 },
  { char: "舌", hanViet: "thiệt", meaning: "cái lưỡi", strokes: 6 },
  { char: "舛", hanViet: "suyễn", meaning: "sai suyễn", strokes: 6 },
  { char: "舟", hanViet: "chu", meaning: "cái thuyền", strokes: 6 },
  { char: "艮", hanViet: "cấn", meaning: "quẻ cấn, dừng", strokes: 6 },
  { char: "色", hanViet: "sắc", meaning: "màu sắc", strokes: 6 },
  { char: "艹", hanViet: "thảo", meaning: "cỏ (biến thể)", strokes: 6 },
  { char: "虍", hanViet: "hổ", meaning: "con hổ", strokes: 6 },
  { char: "虫", hanViet: "trùng", meaning: "sâu bọ", strokes: 6 },
  { char: "血", hanViet: "huyết", meaning: "máu", strokes: 6 },
  { char: "行", hanViet: "hành", meaning: "đi", strokes: 6 },
  { char: "衣", hanViet: "y", meaning: "áo", strokes: 6 },
  { char: "西", hanViet: "tây", meaning: "phía tây", strokes: 6 },
  { char: "見", hanViet: "kiến", meaning: "nhìn, thấy", strokes: 7 },
  { char: "角", hanViet: "giác", meaning: "góc, sừng", strokes: 7 },
  { char: "言", hanViet: "ngôn", meaning: "lời nói", strokes: 7 },
  { char: "谷", hanViet: "cốc", meaning: "thung lũng", strokes: 7 },
  { char: "豆", hanViet: "đậu", meaning: "hạt đậu", strokes: 7 },
  { char: "豕", hanViet: "thỉ", meaning: "con heo", strokes: 7 },
  { char: "豸", hanViet: "trãi", meaning: "loài sâu bọ", strokes: 7 },
  { char: "貝", hanViet: "bối", meaning: "vỏ sò", strokes: 7 },
  { char: "赤", hanViet: "xích", meaning: "màu đỏ", strokes: 7 },
  { char: "走", hanViet: "tẩu", meaning: "chạy", strokes: 7 },
  { char: "足", hanViet: "túc", meaning: "chân", strokes: 7 },
  { char: "身", hanViet: "thân", meaning: "thân thể", strokes: 7 },
  { char: "車", hanViet: "xa", meaning: "xe", strokes: 7 },
  { char: "辛", hanViet: "tân", meaning: "cay", strokes: 7 },
  { char: "辰", hanViet: "thần", meaning: "con rồng", strokes: 7 },
  { char: "辵", hanViet: "sước", meaning: "chợt đi chợt dừng", strokes: 7 },
  { char: "邑", hanViet: "ấp", meaning: "vùng đất, xóm làng", strokes: 7 },
  { char: "酉", hanViet: "dậu", meaning: "con gà", strokes: 7 },
  { char: "釆", hanViet: "biện", meaning: "phân biệt", strokes: 7 },
  { char: "里", hanViet: "lý", meaning: "làng, dặm", strokes: 7 },
  { char: "金", hanViet: "kim", meaning: "kim loại, vàng", strokes: 8 },
  { char: "長", hanViet: "trường", meaning: "dài", strokes: 8 },
  { char: "門", hanViet: "môn", meaning: "cửa", strokes: 8 },
  { char: "阜", hanViet: "phụ", meaning: "gò đất", strokes: 8 },
  { char: "隶", hanViet: "đãi", meaning: "kịp, kịp đến", strokes: 8 },
  { char: "隹", hanViet: "chuy", meaning: "chim đuôi ngắn", strokes: 8 },
  { char: "雨", hanViet: "vũ", meaning: "mưa", strokes: 8 },
  { char: "青", hanViet: "thanh", meaning: "màu xanh", strokes: 8 },
  { char: "非", hanViet: "phi", meaning: "không", strokes: 8 },
  { char: "面", hanViet: "diện", meaning: "mặt", strokes: 9 },
  { char: "革", hanViet: "cách", meaning: "da thú", strokes: 9 },
  { char: "韋", hanViet: "vi", meaning: "da đã thuộc", strokes: 9 },
  { char: "韭", hanViet: "cửu", meaning: "hẹ", strokes: 9 },
  { char: "音", hanViet: "âm", meaning: "âm thanh", strokes: 9 },
  { char: "頁", hanViet: "hiệt", meaning: "trang giấy", strokes: 9 },
  { char: "風", hanViet: "phong", meaning: "gió", strokes: 9 },
  { char: "飛", hanViet: "phi", meaning: "bay", strokes: 9 },
  { char: "食", hanViet: "thực", meaning: "ăn", strokes: 9 },
  { char: "首", hanViet: "thủ", meaning: "đầu", strokes: 9 },
  { char: "香", hanViet: "hương", meaning: "mùi thơm", strokes: 9 },
  { char: "馬", hanViet: "mã", meaning: "ngựa", strokes: 10 },
  { char: "骨", hanViet: "cốt", meaning: "xương", strokes: 10 },
  { char: "高", hanViet: "cao", meaning: "cao", strokes: 10 },
  { char: "髟", hanViet: "tiêu", meaning: "tóc dài", strokes: 10 },
  { char: "鬥", hanViet: "đấu", meaning: "chiến đấu", strokes: 10 },
  { char: "鬯", hanViet: "sưởng", meaning: "rượu nếp", strokes: 10 },
  { char: "鬲", hanViet: "cách", meaning: "cái nồi", strokes: 10 },
  { char: "鬼", hanViet: "quỷ", meaning: "ma quỷ", strokes: 10 },
  { char: "魚", hanViet: "ngư", meaning: "cá", strokes: 11 },
  { char: "鳥", hanViet: "điểu", meaning: "chim", strokes: 11 },
  { char: "鹵", hanViet: "lỗ", meaning: "đất mặn", strokes: 11 },
  { char: "鹿", hanViet: "lộc", meaning: "con hươu", strokes: 11 },
  { char: "麥", hanViet: "mạch", meaning: "lúa mạch", strokes: 11 },
  { char: "麻", hanViet: "ma", meaning: "cây gai", strokes: 11 },
  { char: "黃", hanViet: "hoàng", meaning: "màu vàng", strokes: 12 },
  { char: "黍", hanViet: "thử", meaning: "lúa nếp", strokes: 12 },
  { char: "黒", hanViet: "hắc", meaning: "màu đen", strokes: 12 },
  { char: "黹", hanViet: "chỉ", meaning: "may vá", strokes: 12 },
  { char: "黽", hanViet: "mãnh", meaning: "con ếch", strokes: 13 },
  { char: "鼎", hanViet: "đỉnh", meaning: "cái đỉnh", strokes: 13 },
  { char: "鼓", hanViet: "cổ", meaning: "cái trống", strokes: 13 },
  { char: "鼠", hanViet: "thử", meaning: "con chuột", strokes: 13 },
  { char: "鼻", hanViet: "tỵ", meaning: "cái mũi", strokes: 14 },
  { char: "齊", hanViet: "tề", meaning: "ngay ngắn", strokes: 14 },
  { char: "齒", hanViet: "xỉ", meaning: "răng", strokes: 15 },
  { char: "龍", hanViet: "long", meaning: "con rồng", strokes: 16 },
  { char: "龜", hanViet: "quy", meaning: "con rùa", strokes: 16 },
  { char: "龠", hanViet: "thược", meaning: "cái sáo", strokes: 17 },
];